# action.yml
name: 'CRDA to Sarif '
description: 'This action with take CRDA JSON output and produces a sarif file.'
inputs:
  input-file-name:  
    description: 'This is the source file crom CRDA'
    required: true 
  snyk-token:  
    description: 'This is the sny token for verbose scans'
    required: true 
  output-file-name:  
    description: 'This is the generated Sarif file'
    required: false
    default: 'output.sarif' 
outputs:
  result: 
    description: 'The result of the merging command'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.input-file-name }} 
    - ${{ inputs.snyk-token }} 
    - ${{ inputs.output-file-name }} 
