# action.yml
name: 'CRDA to Sarif '
description: 'This action with take CRDA JSON output and produces a sarif file.'
inputs:
  input-file-name:  
    description: 'This is the source file crom CRDA'
    required: false
    default: 'crda.json' 
outputs:
  result: 
    description: 'The result of the merging command'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.input-file-name }} 
