#CI Test - Build the action container
# build test container which has default test files and validate
name: CI
on: [workflow_dispatch] 
jobs:
  test:
    runs-on: ubuntu-latest
    name: Merge Sarif Files for github scans
    steps: 
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Run CRDA and generate sarif
        uses: ./   
        with:
          input-file-name: package.json
          merged-file-name: ${{ secrets.SNYK_TOKEN }}
      - name: CRDA validate
        run: |  
          cat output.sarif  | jq 
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file:  output.sarif